### ISSUE TITLE
The value variable do not return a value

### ISSUE THREAD

**Issue by antoine2711** [wetneb/refine-js#1]
**Explications**
When using the variable value, the current `value` of the cell should be returned, when now, we only have `null` returned.

![image](https://user-images.githubusercontent.com/12217525/172971469-b6af912b-aabe-4bee-b809-eb4ee5b216ea.png)

**Comment by thadguidry** [comment]
`return value`

See the tests: https://github.com/wetneb/refine-js/blob/master/src/test/java/io/github/wetneb/refinejs/RhinoEvaluableTests.java

**Comment by antoine2711** [comment]
Thanks @thadguidry. Not used to something else than grel… ;-)
